"""字段字典：四种实体的 canonical 字段定义及中英文别名。

每个字段：{key, label, required, type(string/number/date), aliases, unit_hints}
"""

from __future__ import annotations


ENTITY_FIELD_DICT: dict[str, list[dict]] = {
    "sample": [
        {
            "key": "sample_code",
            "label": "业务编号",
            "required": False,
            "type": "string",
            "aliases": ["样品编号", "编号", "业务编号", "sample_code", "SampleCode", "code", "编号/ID"],
            "unit_hints": [],
        },
        {
            "key": "name",
            "label": "名称",
            "required": True,
            "type": "string",
            "aliases": ["名称", "样品名称", "sample_name", "Name", "Sample Name", "品名"],
            "unit_hints": [],
        },
        {
            "key": "chemical_formula",
            "label": "化学式",
            "required": False,
            "type": "string",
            "aliases": ["化学式", "分子式", "chemical_formula", "formula", "Formula", "Chemical Formula", "组成"],
            "unit_hints": [],
        },
        {
            "key": "batch_number",
            "label": "批次号",
            "required": False,
            "type": "string",
            "aliases": ["批次号", "批次", "batch_number", "batch", "Batch", "Batch No", "批号", "lot", "Lot Number"],
            "unit_hints": [],
        },
        {
            "key": "quantity",
            "label": "数量",
            "required": False,
            "type": "number",
            "aliases": ["数量", "quantity", "Quantity", "qty", "重量", "质量", "weight", "Weight", "amount"],
            "unit_hints": ["g", "kg", "mg", "mL", "L", "片"],
        },
        {
            "key": "unit",
            "label": "单位",
            "required": False,
            "type": "string",
            "aliases": ["单位", "unit", "Unit", "计量单位"],
            "unit_hints": [],
        },
        {
            "key": "storage_location",
            "label": "存储位置",
            "required": False,
            "type": "string",
            "aliases": ["存储位置", "存放位置", "位置", "storage_location", "location", "Location", "storage", "库位"],
            "unit_hints": [],
        },
        {
            "key": "storage_condition",
            "label": "存储条件",
            "required": False,
            "type": "string",
            "aliases": ["存储条件", "储存条件", "storage_condition", "condition", "Condition", "保存条件"],
            "unit_hints": [],
        },
        {
            "key": "source_type",
            "label": "来源类型",
            "required": False,
            "type": "string",
            "aliases": ["来源类型", "来源", "source_type", "source", "Source", "Source Type"],
            "unit_hints": [],
        },
        {
            "key": "notes",
            "label": "备注",
            "required": False,
            "type": "string",
            "aliases": ["备注", "notes", "Notes", "note", "remark", "Remark", "说明"],
            "unit_hints": [],
        },
    ],
    "equipment": [
        {
            "key": "equipment_id",
            "label": "设备编号",
            "required": False,
            "type": "string",
            "aliases": ["设备编号", "编号", "equipment_id", "Equipment ID", "asset_id", "资产编号"],
            "unit_hints": [],
        },
        {
            "key": "name",
            "label": "设备名称",
            "required": True,
            "type": "string",
            "aliases": ["名称", "设备名称", "equipment_name", "name", "Name", "Equipment Name"],
            "unit_hints": [],
        },
        {
            "key": "model",
            "label": "型号",
            "required": False,
            "type": "string",
            "aliases": ["型号", "model", "Model", "规格型号", "type"],
            "unit_hints": [],
        },
        {
            "key": "category",
            "label": "类别",
            "required": False,
            "type": "string",
            "aliases": ["类别", "分类", "category", "Category", "设备类别", "type"],
            "unit_hints": [],
        },
        {
            "key": "serial_number",
            "label": "序列号",
            "required": False,
            "type": "string",
            "aliases": ["序列号", "serial_number", "Serial Number", "SN", "sn", "出厂编号"],
            "unit_hints": [],
        },
        {
            "key": "location",
            "label": "位置",
            "required": False,
            "type": "string",
            "aliases": ["位置", "存放位置", "location", "Location", "安装位置"],
            "unit_hints": [],
        },
        {
            "key": "responsible_person",
            "label": "负责人",
            "required": False,
            "type": "string",
            "aliases": ["负责人", "责任人", "responsible_person", "owner", "Owner", "管理人"],
            "unit_hints": [],
        },
        {
            "key": "purchase_date",
            "label": "购置日期",
            "required": False,
            "type": "date",
            "aliases": ["购置日期", "购买日期", "purchase_date", "Purchase Date", "购入日期"],
            "unit_hints": [],
        },
        {
            "key": "last_calibration",
            "label": "上次校准日期",
            "required": False,
            "type": "date",
            "aliases": ["上次校准", "校准日期", "last_calibration", "Last Calibration", "最近校准日期"],
            "unit_hints": [],
        },
        {
            "key": "next_calibration",
            "label": "下次校准日期",
            "required": False,
            "type": "date",
            "aliases": ["下次校准", "next_calibration", "Next Calibration", "校准到期日"],
            "unit_hints": [],
        },
        {
            "key": "notes",
            "label": "备注",
            "required": False,
            "type": "string",
            "aliases": ["备注", "notes", "Notes", "remark", "Remark", "说明"],
            "unit_hints": [],
        },
    ],
    "raw_material": [
        {
            "key": "material_id",
            "label": "物料编号",
            "required": False,
            "type": "string",
            "aliases": ["物料编号", "编号", "material_id", "Material ID", "code", "货号"],
            "unit_hints": [],
        },
        {
            "key": "name",
            "label": "物料名称",
            "required": True,
            "type": "string",
            "aliases": ["名称", "物料名称", "material_name", "name", "Name", "品名", "Material Name"],
            "unit_hints": [],
        },
        {
            "key": "smiles",
            "label": "SMILES",
            "required": False,
            "type": "string",
            "aliases": ["SMILES", "smiles", "Smiles", "结构式"],
            "unit_hints": [],
        },
        {
            "key": "category",
            "label": "类别",
            "required": False,
            "type": "string",
            "aliases": ["类别", "分类", "category", "Category", "物料类别"],
            "unit_hints": [],
        },
        {
            "key": "inventory_quantity",
            "label": "库存量",
            "required": False,
            "type": "number",
            "aliases": ["库存", "库存量", "inventory_kg", "inventory", "Inventory", "stock", "库存(kg)"],
            "unit_hints": ["kg"],
        },
        {
            "key": "unit_cost",
            "label": "单价",
            "required": False,
            "type": "number",
            "aliases": ["单价", "cost_per_kg", "price", "Price", "unit_price", "价格", "单价(元/kg)"],
            "unit_hints": [],
        },
        {
            "key": "supplier",
            "label": "供应商",
            "required": False,
            "type": "string",
            "aliases": ["供应商", "supplier", "Supplier", "vendor", "Vendor", "厂家"],
            "unit_hints": [],
        },
        {
            "key": "batch_number",
            "label": "批次号",
            "required": False,
            "type": "string",
            "aliases": ["批次号", "批次", "batch_number", "batch", "Batch", "批号", "lot"],
            "unit_hints": [],
        },
        {
            "key": "expiry_date",
            "label": "有效期",
            "required": False,
            "type": "date",
            "aliases": ["有效期", "expiry_date", "Expiry Date", "保质期", "失效日期", "expiration"],
            "unit_hints": [],
        },
        {
            "key": "min_order_quantity",
            "label": "最小起订量",
            "required": False,
            "type": "number",
            "aliases": ["最小起订量", "min_order_quantity", "MOQ", "moq", "起订量"],
            "unit_hints": ["kg"],
        },
        # Task 13：合规证据字段 —— REACH/SDS/毒性合规声明必须有凭证支撑
        {
            "key": "coa_uri",
            "label": "COA报告链接",
            "required": False,
            "type": "string",
            "aliases": ["COA", "COA链接", "COA报告", "coa_uri", "COA URI", "COA报告链接", "CoA"],
            "unit_hints": [],
        },
        {
            "key": "sds_uri",
            "label": "SDS报告链接",
            "required": False,
            "type": "string",
            "aliases": ["SDS", "SDS链接", "SDS报告", "sds_uri", "SDS URI", "SDS报告链接", "安全数据表"],
            "unit_hints": [],
        },
        {
            "key": "test_report_uri",
            "label": "检测报告链接",
            "required": False,
            "type": "string",
            "aliases": ["检测报告", "检测报告链接", "test_report_uri", "Test Report URI", "第三方报告", "测试报告"],
            "unit_hints": [],
        },
        {
            "key": "test_institution",
            "label": "检测机构",
            "required": False,
            "type": "string",
            "aliases": ["检测机构", "test_institution", "Test Institution", "检测单位", "实验室"],
            "unit_hints": [],
        },
        {
            "key": "test_date",
            "label": "检测日期",
            "required": False,
            "type": "date",
            "aliases": ["检测日期", "test_date", "Test Date", "报告日期"],
            "unit_hints": [],
        },
    ],
    "experiment_result": [
        {
            "key": "result_id",
            "label": "结果ID",
            "required": False,
            "type": "string",
            "aliases": ["结果ID", "结果编号", "result_id", "Result ID", "记录ID", "record_id"],
            "unit_hints": [],
        },
        {
            "key": "experiment_order_id",
            "label": "实验任务单ID",
            "required": False,
            "type": "string",
            "aliases": ["任务单ID", "order_id", "experiment_order_id", "Order ID", "任务ID", "实验任务单", "实验单号"],
            "unit_hints": [],
        },
        {
            "key": "sample_id",
            "label": "样品ID",
            "required": False,
            "type": "string",
            "aliases": ["样品ID", "样品编号", "sample_id", "Sample ID", "样品"],
            "unit_hints": [],
        },
        {
            "key": "sample_batch_id",
            "label": "样品批次号",
            "required": False,
            "type": "string",
            "aliases": ["样品批次", "批次号", "batch_id", "batch_number", "sample_batch_id", "Batch ID", "Batch", "批次"],
            "unit_hints": [],
        },
        {
            "key": "source_type",
            "label": "来源类型",
            "required": False,
            "type": "string",
            "aliases": ["来源类型", "来源", "source_type", "source", "Source", "Source Type", "数据来源"],
            "unit_hints": [],
        },
        {
            "key": "source_system",
            "label": "来源系统",
            "required": False,
            "type": "string",
            "aliases": ["来源系统", "source_system", "Source System", "系统", "来源系统名称"],
            "unit_hints": [],
        },
        {
            "key": "uploaded_by",
            "label": "录入人",
            "required": False,
            "type": "string",
            "aliases": ["录入人", "操作员", "operator", "uploaded_by", "Operator", "录入者", "上传人"],
            "unit_hints": [],
        },
        {
            "key": "uploaded_at",
            "label": "录入时间",
            "required": False,
            "type": "date",
            "aliases": ["录入时间", "上传时间", "uploaded_at", "Uploaded At", "时间", "timestamp", "created_at"],
            "unit_hints": [],
        },
        {
            "key": "property_name",
            "label": "实验类型/属性",
            "required": True,
            "type": "string",
            "aliases": ["实验类型", "属性名", "experiment_type", "property_name", "Property", "Property Name", "实验项目", "测试项目"],
            "unit_hints": [],
        },
        {
            "key": "value",
            "label": "数值",
            "required": True,
            "type": "number",
            "aliases": ["数值", "值", "value", "Value", "测量值", "结果值", "测得值"],
            "unit_hints": [],
        },
        {
            "key": "unit",
            "label": "单位",
            "required": False,
            "type": "string",
            "aliases": ["单位", "unit", "Unit", "计量单位", "units"],
            "unit_hints": [],
        },
        {
            "key": "test_method",
            "label": "测试方法",
            "required": False,
            "type": "string",
            "aliases": ["测试方法", "实验方法", "test_method", "Test Method", "Method", "方法"],
            "unit_hints": [],
        },
        {
            "key": "test_conditions",
            "label": "测试条件",
            "required": False,
            "type": "string",
            "aliases": ["测试条件", "实验条件", "test_conditions", "Test Conditions", "conditions", "Conditions"],
            "unit_hints": [],
        },
        {
            "key": "instrument_id",
            "label": "设备ID",
            "required": False,
            "type": "string",
            "aliases": ["设备ID", "设备编号", "instrument_id", "Instrument ID", "equipment_id", "Equipment ID", "设备"],
            "unit_hints": [],
        },
        {
            "key": "raw_file_uri",
            "label": "原始文件URI",
            "required": False,
            "type": "string",
            "aliases": ["原始文件", "原始文件URI", "raw_file_uri", "Raw File URI", "原始数据", "源文件"],
            "unit_hints": [],
        },
        {
            "key": "qc_status",
            "label": "QC状态",
            "required": False,
            "type": "string",
            "aliases": ["QC状态", "质量状态", "qc_status", "QC Status", "QC", "质量"],
            "unit_hints": [],
        },
        {
            "key": "qc_issues",
            "label": "QC问题",
            "required": False,
            "type": "string",
            "aliases": ["QC问题", "质量问题", "qc_issues", "QC Issues", "问题列表"],
            "unit_hints": [],
        },
        {
            "key": "reviewed_by",
            "label": "审核人",
            "required": False,
            "type": "string",
            "aliases": ["审核人", "复核人", "reviewed_by", "Reviewed By", "审核者"],
            "unit_hints": [],
        },
        {
            "key": "reviewed_at",
            "label": "审核时间",
            "required": False,
            "type": "date",
            "aliases": ["审核时间", "复核时间", "reviewed_at", "Reviewed At"],
            "unit_hints": [],
        },
        {
            "key": "learning_eligible",
            "label": "可学习",
            "required": False,
            "type": "string",
            "aliases": ["可学习", "learning_eligible", "Learning Eligible", "可用于训练"],
            "unit_hints": [],
        },
        {
            "key": "scenario_id",
            "label": "研发场景ID",
            "required": False,
            "type": "string",
            "aliases": ["研发场景ID", "scenario_id", "Scenario ID", "场景"],
            "unit_hints": [],
        },
    ],
    "project": [
        {
            "key": "name",
            "label": "项目名称",
            "required": True,
            "type": "string",
            "aliases": ["名称", "项目名称", "project_name", "name", "Name", "Project Name", "项目"],
            "unit_hints": [],
        },
        {
            "key": "target_application",
            "label": "目标应用",
            "required": False,
            "type": "string",
            "aliases": ["目标应用", "应用方向", "target_application", "application", "Application", "应用领域"],
            "unit_hints": [],
        },
        {
            "key": "current_stage",
            "label": "当前阶段",
            "required": False,
            "type": "string",
            "aliases": ["当前阶段", "阶段", "current_stage", "stage", "Stage", "项目阶段"],
            "unit_hints": [],
        },
        {
            "key": "owner",
            "label": "负责人",
            "required": False,
            "type": "string",
            "aliases": ["负责人", "owner", "Owner", "项目负责人", "PI", "pi"],
            "unit_hints": [],
        },
        {
            "key": "department",
            "label": "所属部门",
            "required": False,
            "type": "string",
            "aliases": ["所属部门", "部门", "department", "Department", "dept"],
            "unit_hints": [],
        },
        {
            "key": "start_date",
            "label": "计划开始日期",
            "required": False,
            "type": "date",
            "aliases": ["计划开始日期", "开始日期", "start_date", "Start Date", "启动日期"],
            "unit_hints": [],
        },
        {
            "key": "end_date",
            "label": "计划结束日期",
            "required": False,
            "type": "date",
            "aliases": ["计划结束日期", "结束日期", "end_date", "End Date", "完成日期"],
            "unit_hints": [],
        },
        {
            "key": "budget",
            "label": "预算(万元)",
            "required": False,
            "type": "number",
            "aliases": ["预算", "budget", "Budget", "预算(万元)", "经费"],
            "unit_hints": [],
        },
        {
            "key": "iteration_progress",
            "label": "迭代进度(%)",
            "required": False,
            "type": "number",
            "aliases": ["迭代进度", "进度", "iteration_progress", "progress", "Progress"],
            "unit_hints": ["%"],
        },
        {
            "key": "notes",
            "label": "备注",
            "required": False,
            "type": "string",
            "aliases": ["备注", "notes", "Notes", "remark", "Remark", "说明"],
            "unit_hints": [],
        },
    ],
}

ENTITY_TYPES = list(ENTITY_FIELD_DICT.keys())


def get_field_dict(entity_type: str) -> list[dict]:
    """返回指定实体的字段字典，未知实体类型返回空列表。"""
    return ENTITY_FIELD_DICT.get(entity_type, [])
